language: python

python: "2.7"

env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=pypy
    - TOXENV=cov

branches:
    only:
        - master
        - develop

install: pip install --quiet tox

script: tox

after_script:
    - if [ $TOXENV == "cov" ]; then
        pip install --quiet coveralls;
        coveralls;
      fi
